trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageNameFrontend: 'netflix-ui'
  imageNameBackend: 'netflix-api'
  dockerHubConnection: 'rishabh-dockerhub-conn'
  dockerHubUsername: 'rkhosla'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  displayName: 'Build & Push Frontend Image'
  inputs:
    containerRegistry: '$(dockerHubConnection)'
    repository: '$(dockerHubUsername)/$(imageNameFrontend)'
    command: 'buildAndPush'
    Dockerfile: 'netflix-ui/Dockerfile'
    tags: 'latest'

- task: Docker@2
  displayName: 'Build & Push Backend Image'
  inputs:
    containerRegistry: '$(dockerHubConnection)'
    repository: '$(dockerHubUsername)/$(imageNameBackend)'
    command: 'buildAndPush'
    Dockerfile: 'netflix-api/Dockerfile'
    tags: 'latest'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'docker-compose.yml'
    ArtifactName: 'drop'
    publishLocation: 'Container'
